version: "2"

services:
  franka_ros_image:
    build:
      context: .
      dockerfile: Dockerfile
      
    image: franka_ros:0.10.0
    
    container_name: u20.04-franka_ros 

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix    
      - /dev:/dev                        
      - ../docker_volume:/docker_volume 

    environment:
      - DISPLAY=$DISPLAY
      - TZ=Europe/London
    
    network_mode: host
    
    privileged: true

    cap_add:
      - SYS_NICE
    
    tty: true
